<x-layouts.admin title="Detail Penilaian">
    <div class="resource-page-navigation"><a class="primary-button" href="{{ route('admin.assessments.index') }}"><x-lucide-arrow-left aria-hidden="true" /><span>Kembali</span></a></div>
    <div class="detail-layout">
        <x-admin.panel title="Informasi Penilaian"><div class="detail-grid"><x-admin.detail-row label="Waktu Penilaian" :value="$rating->submitted_at?->format('d M Y H:i') ?? '-'" /><x-admin.detail-row label="Unit Kerja" :value="$rating->branch?->name ?? '-'" /><x-admin.detail-row label="Kendaraan" :value="trim(($rating->vehicle?->police_number ?? '').' - '.($rating->vehicle?->brand ?? '').' '.($rating->vehicle?->model ?? ''))" /><x-admin.detail-row label="Driver" :value="$rating->driver?->full_name ?? '-'" /><x-admin.detail-row label="Rating Keseluruhan" :value="$analytics->ratingScore($rating) ?? '-'" /></div></x-admin.panel>
        <x-admin.panel title="Komentar Penumpang"><div class="comment-list">@forelse($comments as $comment)<article><strong>{{ $comment['question'] }}</strong><p>{{ $comment['text'] }}</p></article>@empty<x-admin.empty-state title="Tidak ada komentar" description="Penilaian ini tidak memiliki jawaban teks." />@endforelse</div></x-admin.panel>
    </div>
    @foreach(['driver' => 'Penilaian Driver', 'vehicle' => 'Penilaian Kendaraan'] as $target => $title)
        <x-admin.panel :title="$title"><div class="table-wrap"><table class="data-table"><thead><tr><th>Pertanyaan</th><th>Jawaban</th></tr></thead><tbody>@forelse($rating->answers->filter(fn ($answer) => $answer->question?->target_type === $target) as $answer)@php($optionText = $answer->question?->options->whereIn('id', $answer->answer_value ?? [])->pluck('option_text')->join(', '))<tr><td>{{ $answer->question?->question }}</td><td>@if($answer->question?->answer_type === 'rating'){{ $answer->answer_value[0] ?? '-' }} / 5 @elseif($answer->question?->answer_type === 'yes_no'){{ (int) ($answer->answer_value[0] ?? 0) === 1 ? 'Ya' : 'Tidak' }} @else{{ $answer->answer_text ?: $optionText ?: '-' }}@endif</td></tr>@empty<tr><td colspan="2">Belum ada jawaban {{ strtolower($title) }}.</td></tr>@endforelse</tbody></table></div></x-admin.panel>
    @endforeach
</x-layouts.admin>
