<!DOCTYPE html><html lang="id"><head><meta charset="utf-8"><title>Laporan Monitoring</title><style>@page{margin:14mm}*{box-sizing:border-box}body{font-family:DejaVu Sans,sans-serif;color:#17202a;font-size:10px}header{border-bottom:2px solid #1d4ed8;padding-bottom:10px;margin-bottom:18px}h1{font-size:18px;margin:0 0 5px}h2{font-size:13px;margin:20px 0 8px}.meta{color:#64748b}.summary{background:#eff6ff;border:1px solid #bfdbfe;padding:12px;margin-bottom:14px}.summary strong{font-size:20px;color:#1d4ed8}table{border-collapse:collapse;width:100%}th,td{border:1px solid #cbd5e1;padding:7px;text-align:left}th{background:#f1f5f9}.right{text-align:right}.muted{color:#64748b}</style></head><body>
@php($detail = $report['detail'])
<header><h1>Laporan Monitoring {{ $report['type'] === 'driver' ? 'Driver' : 'Kendaraan' }}</h1><div class="meta">{{ $report['branch']->name }} &middot; {{ $report['period']->translatedFormat('F Y') }}</div></header>
@if($report['type'] === 'driver')
<div class="summary"><b>{{ $detail['driver']->full_name }}</b><br>NIK: DRV-{{ $report['branch']->code }}-{{ str_pad((string)$detail['driver']->id, 3, '0', STR_PAD_LEFT) }}<br><br>Nilai akhir: <strong>{{ $detail['final_score'] !== null ? number_format($detail['final_score'], 1) : '-' }}</strong></div>
<h2>Ringkasan</h2><table><tr><th>Nilai Driver</th><th>Nilai Absensi</th><th>Total Penilaian</th></tr><tr><td>{{ $detail['driver_score'] !== null ? number_format($detail['driver_score'], 1) : '-' }}</td><td>{{ $detail['attendance_score'] !== null ? number_format($detail['attendance_score'], 1) : '-' }}</td><td>{{ $detail['rating_count'] }}</td></tr></table>
<h2>Kendaraan yang Dinilai Bersama Driver Ini</h2><table><thead><tr><th>No</th><th>Nomor Polisi</th><th>Kendaraan</th><th>Jumlah Penilaian</th><th>Nilai Kendaraan</th></tr></thead><tbody>@forelse($report['related_vehicles'] as $row)<tr><td>{{ $loop->iteration }}</td><td>{{ $row['vehicle']->police_number }}</td><td>{{ trim($row['vehicle']->brand.' '.$row['vehicle']->model) }}</td><td>{{ $row['rating_count'] }}</td><td>{{ $row['vehicle_score'] !== null ? number_format($row['vehicle_score'], 1) : '-' }}</td></tr>@empty<tr><td colspan="5">Belum ada kendaraan terkait pada periode ini.</td></tr>@endforelse</tbody></table>
@else
<div class="summary"><b>{{ $detail['vehicle']->police_number }}</b><br>{{ trim($detail['vehicle']->brand.' '.$detail['vehicle']->model) }}<br><br>Nilai kendaraan: <strong>{{ $detail['vehicle_score'] !== null ? number_format($detail['vehicle_score'], 1) : '-' }}</strong></div>
<h2>Driver Berdasarkan Riwayat Penilaian</h2><table><thead><tr><th>No</th><th>Nama Driver</th><th>Kategori</th></tr></thead><tbody>@forelse($detail['drivers'] as $driver)<tr><td>{{ $loop->iteration }}</td><td>{{ $driver->full_name }}</td><td>{{ $driver->employeeCategory?->name ?? 'Driver' }}</td></tr>@empty<tr><td colspan="3">Belum ada driver terkait pada periode ini.</td></tr>@endforelse</tbody></table>
@endif
<h2>Rincian Indikator</h2><table><thead><tr><th>Indikator</th><th class="right">Rata-rata</th><th class="right">Persentase</th></tr></thead><tbody>@forelse($detail['question_breakdown'] as $item)<tr><td>{{ $item['question']->indicator ?: $item['question']->question }}</td><td class="right">{{ number_format($item['average'], 1) }}/5</td><td class="right">{{ number_format($item['percentage'], 1) }}%</td></tr>@empty<tr><td colspan="3">Belum ada rincian penilaian.</td></tr>@endforelse</tbody></table>
</body></html>
