<x-layouts.admin title="Detail Monitoring">
    <x-slot:pageActions><div class="monitoring-detail-actions">
        <a class="secondary-button" href="{{ route('admin.monitoring.index', ['period' => $period->format('Y-m'), 'target' => $target]) }}"><x-lucide-arrow-left aria-hidden="true" /><span>Kembali</span></a>
        <form method="GET"><label class="native-picker-field"><span>Periode</span><input type="month" name="period" value="{{ $period->format('Y-m') }}" onchange="this.form.requestSubmit()"></label><input type="hidden" name="target" value="{{ $target }}"><input type="hidden" name="status" value="{{ $status }}">@if(request()->filled('period') || request()->filled('status'))<a class="secondary-button assessment-reset-button" href="{{ route('admin.monitoring.show', [$branch, 'target' => $target]) }}"><x-lucide-rotate-ccw aria-hidden="true" /><span>Reset</span></a>@endif</form>
        <a class="monitoring-print-button" data-no-loading href="{{ route('admin.monitoring.branch.report', [$branch, 'period' => $period->format('Y-m')]) }}"><x-lucide-printer aria-hidden="true" /><span>Cetak</span></a>
    </div></x-slot>

    <div class="monitoring-intro monitoring-detail-intro"><h2>Unit Kerja: {{ $branch->name }}</h2><p>{{ $branch->regency ?: 'Wilayah operasional belum tersedia' }} &middot; Periode {{ $period->translatedFormat('F Y') }}</p></div>
    <nav class="recruitment-tabs" aria-label="Jenis data monitoring">
        <a @class(['is-active' => $target === 'driver']) href="{{ route('admin.monitoring.show', [$branch, 'period' => $period->format('Y-m'), 'target' => 'driver']) }}"><x-lucide-users aria-hidden="true" /><span>Driver</span></a>
        <a @class(['is-active' => $target === 'vehicle']) href="{{ route('admin.monitoring.show', [$branch, 'period' => $period->format('Y-m'), 'target' => 'vehicle']) }}"><x-lucide-car aria-hidden="true" /><span>Kendaraan</span></a>
    </nav>

    <section class="monitoring-panel">
        <header class="monitoring-panel-header"><div><h3>{{ $target === 'vehicle' ? 'Daftar Kendaraan' : 'Daftar Driver' }}</h3><p>{{ $target === 'vehicle' ? 'Tinjau hasil penilaian kendaraan pada periode ini.' : 'Kelola absensi dan tinjau hasil penilaian driver.' }}</p></div>
            <nav class="monitoring-status-tabs"><a @class(['is-active' => !in_array($status, ['complete', 'incomplete'], true)]) href="{{ route('admin.monitoring.show', [$branch, 'period' => $period->format('Y-m'), 'target' => $target]) }}">Semua</a><a @class(['is-active' => $status === 'complete']) href="{{ route('admin.monitoring.show', [$branch, 'period' => $period->format('Y-m'), 'target' => $target, 'status' => 'complete']) }}">{{ $target === 'vehicle' ? 'Sudah Dinilai' : 'Lengkap' }}</a><a @class(['is-active' => $status === 'incomplete']) href="{{ route('admin.monitoring.show', [$branch, 'period' => $period->format('Y-m'), 'target' => $target, 'status' => 'incomplete']) }}">{{ $target === 'vehicle' ? 'Belum Dinilai' : 'Belum Lengkap' }}</a></nav>
        </header>
        <div class="table-wrap"><table class="data-table monitoring-table monitoring-driver-table">
            @if($target === 'vehicle')
                <thead><tr><th>Kendaraan</th><th>Penilaian Terakhir</th><th>Total Penilaian</th><th>Driver Terkait</th><th>Nilai Kendaraan</th><th>Status</th><th>Aksi</th></tr></thead>
                <tbody>@forelse($rows as $row)@php($vehicle = $row['vehicle'])<tr><td><strong>{{ $vehicle->police_number }}</strong><small>{{ trim($vehicle->brand.' '.$vehicle->model) ?: 'Detail kendaraan belum tersedia' }}</small></td><td>{{ $row['latest_rating']?->submitted_at?->timezone(config('app.display_timezone'))->translatedFormat('d M Y') ?? '-' }}</td><td><strong>{{ $row['rating_count'] }}</strong></td><td><strong>{{ $row['driver_count'] }}</strong><small>berdasarkan penilaian</small></td><td><strong class="monitoring-score">{{ $row['vehicle_score'] !== null ? number_format($row['vehicle_score'], 1) : '-' }}</strong></td><td><span @class(['monitoring-completeness', 'is-complete' => $row['has_ratings'], 'is-incomplete' => !$row['has_ratings']])>{{ $row['has_ratings'] ? 'Sudah Dinilai' : 'Belum Dinilai' }}</span></td><td><div class="monitoring-row-actions"><a class="monitoring-icon-button" href="{{ route('admin.monitoring.vehicle', [$branch, $vehicle, 'period' => $period->format('Y-m')]) }}" title="Lihat detail"><x-lucide-eye aria-hidden="true" /></a><a class="monitoring-icon-button" data-no-loading href="{{ route('admin.monitoring.vehicle.export', [$branch, $vehicle, 'period' => $period->format('Y-m')]) }}" title="Download PDF"><x-lucide-download aria-hidden="true" /></a></div></td></tr>@empty<tr><td colspan="7"><x-admin.empty-state title="Belum ada kendaraan" description="Tidak ada kendaraan aktif yang sesuai dengan filter." /></td></tr>@endforelse</tbody>
            @else
                <thead><tr><th>Driver &amp; Identitas</th><th>Kendaraan Terbaru</th><th>Rekap H/S/I/A</th><th>Nilai Driver</th><th>Nilai Absensi</th><th>Nilai Akhir</th><th>Status</th><th>Aksi</th></tr></thead>
                <tbody>@forelse($rows as $row)@php($driver = $row['driver'])@php($attendance = $row['attendance'])<tr>
                    <td><div class="monitoring-driver"><span class="monitoring-avatar"><x-entity-photo type="driver" :src="$driver->photo" alt="Foto {{ $driver->full_name }}" /></span><span><strong>{{ $driver->full_name }}</strong><small>NIK: DRV-{{ $branch->code }}-{{ str_pad((string) $driver->id, 3, '0', STR_PAD_LEFT) }}</small></span></div></td><td>@if($row['vehicle'])<strong>{{ trim($row['vehicle']->brand.' '.$row['vehicle']->model) }}</strong><small>{{ $row['vehicle']->police_number }}</small>@else-@endif</td><td>{{ $attendance ? "$attendance->present_days/$attendance->sick_days/$attendance->permitted_days/$attendance->absent_days" : '-' }}</td><td><strong class="monitoring-score">{{ $row['driver_score'] !== null ? number_format($row['driver_score'], 1) : '-' }}</strong><small>{{ $row['rating_count'] }} penilaian</small></td><td><strong>{{ $row['attendance_score'] !== null ? number_format($row['attendance_score'], 1) : '-' }}</strong></td><td><strong class="monitoring-final-score">{{ $row['final_score'] !== null ? number_format($row['final_score'], 1) : '-' }}</strong></td><td><span @class(['monitoring-completeness', 'is-complete' => $row['is_complete'], 'is-incomplete' => !$row['is_complete']])>{{ $row['is_complete'] ? 'Lengkap' : 'Belum Lengkap' }}</span></td>
                    <td><div class="monitoring-row-actions"><button class="monitoring-update-button" type="button" data-attendance-open data-driver-id="{{ $driver->id }}" data-action="{{ route('admin.monitoring.attendance.store', [$branch, $driver]) }}" data-driver="{{ $driver->full_name }}" data-identity="DRV-{{ $branch->code }}-{{ str_pad((string) $driver->id, 3, '0', STR_PAD_LEFT) }}" data-present="{{ $attendance?->present_days ?? 0 }}" data-sick="{{ $attendance?->sick_days ?? 0 }}" data-permitted="{{ $attendance?->permitted_days ?? 0 }}" data-absent="{{ $attendance?->absent_days ?? 0 }}">{{ $attendance ? 'Update Absensi' : 'Input Absensi' }}</button><a class="monitoring-icon-button" href="{{ route('admin.monitoring.driver', [$branch, $driver, 'period' => $period->format('Y-m')]) }}" title="Lihat detail"><x-lucide-eye aria-hidden="true" /></a><a class="monitoring-icon-button" data-no-loading href="{{ route('admin.monitoring.driver.export', [$branch, $driver, 'period' => $period->format('Y-m')]) }}" title="Download PDF"><x-lucide-download aria-hidden="true" /></a></div></td></tr>@empty<tr><td colspan="8"><x-admin.empty-state title="Belum ada driver" description="Tidak ada driver aktif yang sesuai dengan filter." /></td></tr>@endforelse</tbody>
            @endif
        </table></div>
        <footer class="monitoring-panel-footer"><span>{{ $rows->total() }} {{ $target === 'vehicle' ? 'kendaraan' : 'driver' }}</span>@if($rows->hasPages())<x-admin.pagination :paginator="$rows" label="Pagination monitoring" />@endif</footer>
    </section>

    @if($target === 'driver')<div class="monitoring-modal" data-attendance-modal data-attendance-max-days="{{ $workingDays }}" data-error-driver-id="{{ old('attendance_driver_id') }}" hidden><button class="monitoring-modal-backdrop" type="button" data-attendance-close aria-label="Tutup modal"></button><section class="monitoring-modal-card" role="dialog" aria-modal="true"><header><div><h3>Input Absensi Driver</h3><p>Periode {{ $period->translatedFormat('F Y') }}</p></div><button class="monitoring-modal-close" type="button" data-attendance-close><x-lucide-x aria-hidden="true" /></button></header><div class="monitoring-modal-context"><strong data-attendance-driver>Driver</strong><span data-attendance-identity></span></div><form method="POST" data-attendance-form>@csrf<input type="hidden" name="period" value="{{ $period->format('Y-m') }}"><input type="hidden" name="attendance_driver_id" value="{{ old('attendance_driver_id') }}"><div class="monitoring-attendance-grid">@foreach(['present_days' => 'Hadir', 'sick_days' => 'Sakit', 'permitted_days' => 'Izin', 'absent_days' => 'Alpha'] as $field => $label)<label><span>{{ $label }}</span><input type="number" min="0" max="{{ $workingDays }}" name="{{ $field }}" value="0" required></label>@endforeach</div><div class="monitoring-score-preview"><span>Perkiraan Nilai Absensi</span><strong data-attendance-score>0.0</strong><small>Total hari: <b data-attendance-total>0</b> dari {{ $workingDays }}</small></div>@if($errors->any())<div class="monitoring-form-error">{{ $errors->first() }}</div>@endif<footer><button class="secondary-button" type="button" data-attendance-close>Batal</button><button class="primary-button" type="submit"><x-lucide-save aria-hidden="true" /> Simpan</button></footer></form></section></div>@endif
</x-layouts.admin>
